### ISSUE TITLE
support purescript 0.10

### ISSUE THREAD

**Issue by zhangchiqing** [dicefm/purescript-node-mongodb#24]
Any plan to support purescript 0.10.x?

**Comment by SimonRichardson** [comment]
Maybe at some point, I've not had chance to have a look at purescript for some time. I'm more that willing to accept PRs though if I've not got around to it!

**Comment by zhangchiqing** [comment]
Hi @SimonRichardson 

Yes, I [forked the repo](https://github.com/zhangchiqing/purescript-node-mongodb) to upgrade from 0.9 to 0.10. But I'm stuck at a problem that can't figure out. 

I converted [the example](https://github.com/zhangchiqing/purescript-node-mongodb/blob/master/examples/Examples/Database/Mongo/Insert.purs) into [test case](https://github.com/zhangchiqing/purescript-node-mongodb/blob/master/test/Database/Mongo/Insert.purs). However, when I run the tests to test document insertion, the document was inserted, but I also got this error:

```
* Build successful.
* Running tests...
Testing purescript-node-mongodb
Testing Insert
connecting db
db connected
Event { name: (Just "Wow")}
/Users/leo/zhangchiqing/purescript-node-mongodb/node_modules/mongodb/lib/utils.js:98
    process.nextTick(function() { throw err; });
                                  ^

Error: "Couldn't decode Either: Value is not an Object"
    at Object.exports.error (/Users/leo/zhangchiqing/purescript-node-mongodb/output/Control.Monad.Eff.Exception/foreign.js:8:10)
    at cb$prime (/Users/leo/zhangchiqing/purescript-node-mongodb/output/Database.Mongo.Mongo/index.js:61:71)
    at /Users/leo/zhangchiqing/purescript-node-mongodb/output/Database.Mongo.Mongo/foreign.js:73:27
    at /Users/leo/zhangchiqing/purescript-node-mongodb/node_modules/mongodb/lib/collection.js:436:18
    at handleCallback (/Users/leo/zhangchiqing/purescript-node-mongodb/node_modules/mongodb/lib/utils.js:95:56)
    at /Users/leo/zhangchiqing/purescript-node-mongodb/node_modules/mongodb/lib/collection.js:741:5
    at /Users/leo/zhangchiqing/purescript-node-mongodb/node_modules/mongodb-core/lib/connection/pool.js:457:18
    at _combinedTickCallback (internal/process/next_tick.js:67:7)
    at process._tickCallback (internal/process/next_tick.js:98:9)
* ERROR: Subcommand terminated with exit code 1
```

The error is from decoding the mongo write result into json. For some reason, [`decodeJson`](https://github.com/zhangchiqing/purescript-node-mongodb/blob/master/src/Database/Mongo/Results.purs#L22) here is called with `1`, which is a Number, not an Object, so it crashes.

Can I get some help on it?

**Comment by SimonRichardson** [comment]
:thinking: It's strange, because it seems to be throwing from the cancelling of the `findOne`, which I don't get!

I've not purescript installed atm, but hopefully I'll get sometime to dig into this.

**Comment by zhangchiqing** [comment]
Thanks @SimonRichardson 

I debugged a bit. [The exception is from this line `ok       <- obj .? "ok"`](https://github.com/zhangchiqing/purescript-node-mongodb/blob/master/src/Database/Mongo/Results.purs#L23)

This screen shows `decodeJson` was called with `{ ok: 1, n: 1}` by `decodeStrMap`, which is good.
<img width="1186" alt="screen shot 2017-01-08 at 2 51 16 pm" src="https://cloud.githubusercontent.com/assets/811374/21754286/226a7f56-d5b2-11e6-9e64-1456779955e6.png">

But then, `decodeJsonEither` was called with `json = 1` by `getField`, which is `.?`. Since `1` is not an Object, it started crashing
<img width="1173" alt="screen shot 2017-01-08 at 2 51 57 pm" src="https://cloud.githubusercontent.com/assets/811374/21754289/258b064c-d5b2-11e6-9cb0-20658d2543bc.png">

<img width="1179" alt="screen shot 2017-01-08 at 2 52 18 pm" src="https://cloud.githubusercontent.com/assets/811374/21754290/2885ae6a-d5b2-11e6-991e-8d50160bd142.png">

My environment is:

```
Pulp version 10.0.0
psc version 0.10.5 using /Users/leo/.nvm/versions/node/v6.9.1/bin/psc
node 6.9.1
mongodb: 2.6
```

**Comment by SimonRichardson** [comment]
At a guess I would assume it's to do with the way I implemented the bson recursion and probably the fact that maybe purescript might not use the same property names anymore?

https://github.com/dicefm/purescript-node-mongodb/blob/master/src/Database/Mongo/Bson/BsonValue.js#L16

Maybe have a quick look here?

**Comment by zhangchiqing** [comment]
Do you mean the problem is from the foreign function `unsafeToBsonObject`?

I don't think so. My test case is testing `insertOne` which isn't calling `unsafeToBsonObject`, instead, it's calling `encodeJson`
https://github.com/zhangchiqing/purescript-node-mongodb/blob/master/src/Database/Mongo/Mongo.purs#L203

I took a look at the implementation of `encodeJsonWriteResult`, I don't understand why it just simply returns a `jsonEmptyObject`. I updated to [return the json with the property fields](https://github.com/zhangchiqing/purescript-node-mongodb/commit/c5da71cd9f1ecd8dfda451cbf6f9e8996c3d6ce6), but still it doesn't solve this crash issue :(

**Comment by SimonRichardson** [comment]
It's because of changes to Purescript, which has had a knock on effect to Argonaut. It now won't infer the type `Either String Int` as `Int` at runtime, must have worked before! Consequences of a foreign dynamic type meeting and strict types, errors to be had! The code is wrong originally and now is right (see below), so instead it bails out at runtime because it actually just returns `Int` in [jsNumberToBool](https://github.com/dicefm/purescript-node-mongodb/blob/master/src/Database/Mongo/Results.purs#L40). There is even a warning about it! :neutral_face: 

Anyway, just changing the type signature back to `jsNumberToBool :: Int -> Boolean` and then correctly changing to the following, should allow it to work just fine!

```purescript
jsNumberToBool :: Int -> Boolean
jsNumberToBool e = case e of
  1 -> true
  _ -> false
```

**Comment by zhangchiqing** [comment]
Awesome! It worked.

Thanks for the help @SimonRichardson. I'm going to put together the fix and other tests in a PR for review!

**Comment by SimonRichardson** [comment]
I finally got time to install purescript again!

Note we could actually use https://github.com/purescript/purescript-unsafe-coerce and cheat a bit about the underlying type (anything above 0 is true), but I thought that might lead to more troubles down the line.
